# Задача 44
В ячейке ниже представлен код генерирующий <u>_DataFrame_</u>, которая состоит всего из 1 столбца. Ваша задача перевести его в <u>_one hot_</u> вид. Сможете ли вы это сделать без <u>_get_dummies_</u>?
```python
import random  
lst = ['robot'] * 10  
lst += ['human'] * 10  
random.shuffle(lst)  
data = pd.DataFrame({'whoAmI':lst})  
data.head()
```

In [1]:
import pandas as pd
import random 
lst = ['robot'] * 10  
lst += ['human'] * 10  
random.shuffle(lst)  
data = pd.DataFrame({'whoAmI':lst})
data.head(10)

ModuleNotFoundError: No module named 'pandas'

In [ ]:
# Метод get_dummies
pd.get_dummies(data['whoAmI']).head(10)

   human  robot
0      0      1
1      1      0
2      1      0
3      1      0
4      1      0
5      0      1
6      0      1
7      0      1
8      0      1
9      1      0

In [ ]:
# Без метода get_dummies
pd.DataFrame({'human': data['whoAmI'] == 'human',
              'robot': data['whoAmI'] == 'robot'}).astype(int).head(10)

   human  robot
0      0      1
1      1      0
2      1      0
3      1      0
4      1      0
5      0      1
6      0      1
7      0      1
8      0      1
9      1      0